# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ariel/Ariel/Task

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ariel/Ariel/Task

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ariel/Ariel/Task/CMakeFiles /home/ariel/Ariel/Task/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ariel/Ariel/Task/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_server

# Build rule for target.
test_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_server
.PHONY : test_server

# fast build rule for target.
test_server/fast:
	$(MAKE) -f CMakeFiles/test_server.dir/build.make CMakeFiles/test_server.dir/build
.PHONY : test_server/fast

#=============================================================================
# Target rules for targets named test_client

# Build rule for target.
test_client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_client
.PHONY : test_client

# fast build rule for target.
test_client/fast:
	$(MAKE) -f CMakeFiles/test_client.dir/build.make CMakeFiles/test_client.dir/build
.PHONY : test_client/fast

# target to build an object file
src_client/ClientTCP.o:
	$(MAKE) -f CMakeFiles/test_client.dir/build.make CMakeFiles/test_client.dir/src_client/ClientTCP.o
.PHONY : src_client/ClientTCP.o

# target to preprocess a source file
src_client/ClientTCP.i:
	$(MAKE) -f CMakeFiles/test_client.dir/build.make CMakeFiles/test_client.dir/src_client/ClientTCP.i
.PHONY : src_client/ClientTCP.i

# target to generate assembly for a file
src_client/ClientTCP.s:
	$(MAKE) -f CMakeFiles/test_client.dir/build.make CMakeFiles/test_client.dir/src_client/ClientTCP.s
.PHONY : src_client/ClientTCP.s

# target to build an object file
src_client/ClientUDP.o:
	$(MAKE) -f CMakeFiles/test_client.dir/build.make CMakeFiles/test_client.dir/src_client/ClientUDP.o
.PHONY : src_client/ClientUDP.o

# target to preprocess a source file
src_client/ClientUDP.i:
	$(MAKE) -f CMakeFiles/test_client.dir/build.make CMakeFiles/test_client.dir/src_client/ClientUDP.i
.PHONY : src_client/ClientUDP.i

# target to generate assembly for a file
src_client/ClientUDP.s:
	$(MAKE) -f CMakeFiles/test_client.dir/build.make CMakeFiles/test_client.dir/src_client/ClientUDP.s
.PHONY : src_client/ClientUDP.s

# target to build an object file
src_client/main.o:
	$(MAKE) -f CMakeFiles/test_client.dir/build.make CMakeFiles/test_client.dir/src_client/main.o
.PHONY : src_client/main.o

# target to preprocess a source file
src_client/main.i:
	$(MAKE) -f CMakeFiles/test_client.dir/build.make CMakeFiles/test_client.dir/src_client/main.i
.PHONY : src_client/main.i

# target to generate assembly for a file
src_client/main.s:
	$(MAKE) -f CMakeFiles/test_client.dir/build.make CMakeFiles/test_client.dir/src_client/main.s
.PHONY : src_client/main.s

# target to build an object file
src_server/ManipStr.o:
	$(MAKE) -f CMakeFiles/test_server.dir/build.make CMakeFiles/test_server.dir/src_server/ManipStr.o
.PHONY : src_server/ManipStr.o

# target to preprocess a source file
src_server/ManipStr.i:
	$(MAKE) -f CMakeFiles/test_server.dir/build.make CMakeFiles/test_server.dir/src_server/ManipStr.i
.PHONY : src_server/ManipStr.i

# target to generate assembly for a file
src_server/ManipStr.s:
	$(MAKE) -f CMakeFiles/test_server.dir/build.make CMakeFiles/test_server.dir/src_server/ManipStr.s
.PHONY : src_server/ManipStr.s

# target to build an object file
src_server/Server.o:
	$(MAKE) -f CMakeFiles/test_server.dir/build.make CMakeFiles/test_server.dir/src_server/Server.o
.PHONY : src_server/Server.o

# target to preprocess a source file
src_server/Server.i:
	$(MAKE) -f CMakeFiles/test_server.dir/build.make CMakeFiles/test_server.dir/src_server/Server.i
.PHONY : src_server/Server.i

# target to generate assembly for a file
src_server/Server.s:
	$(MAKE) -f CMakeFiles/test_server.dir/build.make CMakeFiles/test_server.dir/src_server/Server.s
.PHONY : src_server/Server.s

# target to build an object file
src_server/ServerTCP.o:
	$(MAKE) -f CMakeFiles/test_server.dir/build.make CMakeFiles/test_server.dir/src_server/ServerTCP.o
.PHONY : src_server/ServerTCP.o

# target to preprocess a source file
src_server/ServerTCP.i:
	$(MAKE) -f CMakeFiles/test_server.dir/build.make CMakeFiles/test_server.dir/src_server/ServerTCP.i
.PHONY : src_server/ServerTCP.i

# target to generate assembly for a file
src_server/ServerTCP.s:
	$(MAKE) -f CMakeFiles/test_server.dir/build.make CMakeFiles/test_server.dir/src_server/ServerTCP.s
.PHONY : src_server/ServerTCP.s

# target to build an object file
src_server/ServerUDP.o:
	$(MAKE) -f CMakeFiles/test_server.dir/build.make CMakeFiles/test_server.dir/src_server/ServerUDP.o
.PHONY : src_server/ServerUDP.o

# target to preprocess a source file
src_server/ServerUDP.i:
	$(MAKE) -f CMakeFiles/test_server.dir/build.make CMakeFiles/test_server.dir/src_server/ServerUDP.i
.PHONY : src_server/ServerUDP.i

# target to generate assembly for a file
src_server/ServerUDP.s:
	$(MAKE) -f CMakeFiles/test_server.dir/build.make CMakeFiles/test_server.dir/src_server/ServerUDP.s
.PHONY : src_server/ServerUDP.s

# target to build an object file
src_server/main.o:
	$(MAKE) -f CMakeFiles/test_server.dir/build.make CMakeFiles/test_server.dir/src_server/main.o
.PHONY : src_server/main.o

# target to preprocess a source file
src_server/main.i:
	$(MAKE) -f CMakeFiles/test_server.dir/build.make CMakeFiles/test_server.dir/src_server/main.i
.PHONY : src_server/main.i

# target to generate assembly for a file
src_server/main.s:
	$(MAKE) -f CMakeFiles/test_server.dir/build.make CMakeFiles/test_server.dir/src_server/main.s
.PHONY : src_server/main.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test_server"
	@echo "... test_client"
	@echo "... src_client/ClientTCP.o"
	@echo "... src_client/ClientTCP.i"
	@echo "... src_client/ClientTCP.s"
	@echo "... src_client/ClientUDP.o"
	@echo "... src_client/ClientUDP.i"
	@echo "... src_client/ClientUDP.s"
	@echo "... src_client/main.o"
	@echo "... src_client/main.i"
	@echo "... src_client/main.s"
	@echo "... src_server/ManipStr.o"
	@echo "... src_server/ManipStr.i"
	@echo "... src_server/ManipStr.s"
	@echo "... src_server/Server.o"
	@echo "... src_server/Server.i"
	@echo "... src_server/Server.s"
	@echo "... src_server/ServerTCP.o"
	@echo "... src_server/ServerTCP.i"
	@echo "... src_server/ServerTCP.s"
	@echo "... src_server/ServerUDP.o"
	@echo "... src_server/ServerUDP.i"
	@echo "... src_server/ServerUDP.s"
	@echo "... src_server/main.o"
	@echo "... src_server/main.i"
	@echo "... src_server/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

